#!/usr/bin/env python3

"""Add custom configs and default values"""
from fvcore.common.config import CfgNode

#pylint: disable=line-too-long

def add_custom_config(cfg):
    """Add custom configs."""
    cfg.DATA.PATH_TO_TROKEN_PT_DATA = '/fs/cfar-projects/actionloc/bounce_back/camera_ready/data/trokens_pt_data/'

    #wandb config
    cfg.WANDB = CfgNode()
    cfg.WANDB.PROJECT = 'trokens'
    cfg.WANDB.ENTITY = 'act_seg_pi_umd'
    cfg.WANDB.ID = ''
    cfg.WANDB.EXP_NAME = ''

    # few shot config
    cfg.FEW_SHOT = CfgNode()
    cfg.FEW_SHOT.N_WAY = 5
    cfg.FEW_SHOT.K_SHOT = 1
    cfg.FEW_SHOT.TRAIN_QUERY_PER_CLASS = 6
    cfg.FEW_SHOT.TEST_QUERY_PER_CLASS = 1
    cfg.FEW_SHOT.TRAIN_EPISODES = 100000
    cfg.FEW_SHOT.TEST_EPISODES = 10000
    cfg.FEW_SHOT.PATCH_TOKENS_AGG = 'spatial'
    cfg.FEW_SHOT.USE_MODEL = True
    cfg.FEW_SHOT.DIST_NORM = 'none'
    cfg.FEW_SHOT.TRAIN_OG_EPISODES = False
    cfg.FEW_SHOT.CLASS_LOSS_LAMBDA = 1.0
    cfg.FEW_SHOT.Q2S_LOSS_LAMBDA = 1.0
    cfg.FEW_SHOT.SUPPORT_TEXT_FUSION = CfgNode()
    cfg.FEW_SHOT.SUPPORT_TEXT_FUSION.ENABLE = False
    cfg.FEW_SHOT.SUPPORT_TEXT_FUSION.TEXT_WEIGHT = 1.0
    cfg.FEW_SHOT.SUPPORT_TEXT_FUSION.VISUAL_WEIGHT = 1.0
    cfg.FEW_SHOT.SUPPORT_TEXT_FUSION.VISUAL_DETACH = True
    cfg.FEW_SHOT.COST_AGG = CfgNode()
    cfg.FEW_SHOT.COST_AGG.ENABLE = False
    cfg.FEW_SHOT.COST_AGG.COST_DIM = 32
    cfg.FEW_SHOT.COST_AGG.GUIDANCE_DIM = 32
    cfg.FEW_SHOT.COST_AGG.NUM_HEADS = 4
    cfg.FEW_SHOT.COST_AGG.WINDOW_SIZE = 4
    cfg.FEW_SHOT.COST_AGG.NUM_LAYERS = 1
    cfg.FEW_SHOT.COST_AGG.MLP_RATIO = 4.0
    cfg.FEW_SHOT.COST_AGG.ATTN_DROPOUT = 0.0
    cfg.FEW_SHOT.COST_AGG.PROJ_DROPOUT = 0.0
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG = CfgNode()
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.ENABLE = False
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.GUIDANCE_DIM = 32
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.NUM_HEADS = 4
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.ATTENTION_TYPE = "full"
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.POOLING_SIZE = 1
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.PAD_LEN = 0
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.MLP_RATIO = 4.0
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.GATE_INIT = 0.0
    cfg.FEW_SHOT.TEXT_ALIGN = CfgNode()
    cfg.FEW_SHOT.TEXT_ALIGN.ENABLE = False
    cfg.FEW_SHOT.TEXT_ALIGN.LOSS_WEIGHT = 0.1
    cfg.FEW_SHOT.TEXT_ALIGN.LOGIT_SCALE = 10.0
    cfg.FEW_SHOT.POT_ROUTE = CfgNode()
    cfg.FEW_SHOT.POT_ROUTE.ENABLE = False
    cfg.FEW_SHOT.POT_ROUTE.FRAME_SOFTMAX_TAU = 0.07
    cfg.FEW_SHOT.POT_ROUTE.QUERY_PARTIAL_ENABLE = False
    cfg.FEW_SHOT.POT_ROUTE.QUERY_PARTIAL_LOGIT_ALPHA = 10.0
    cfg.FEW_SHOT.POT_ROUTE.QUERY_PARTIAL_LOGIT_BIAS = -2.0
    cfg.FEW_SHOT.QUERY_NULL_ROUTE = CfgNode()
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.ENABLE = False
    # Calibrated for cardinality correction at tau=0.04. A 0.25 start
    # saturates the Null mass on positive Query candidates.
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.SCORE_INIT = 0.07
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.SCORE_MIN = -0.20
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.SCORE_MAX = 0.80
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.CARDINALITY_CORRECTION = True
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.TOKEN_INIT_STD = 0.02
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.VALUE_SCALE = 1.0
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.DETACH_FRAME_SCALE = True
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.ORTHO_WEIGHT = 0.01
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.ORTHO_DETACH_SUPPORT = True

    # point info config
    cfg.POINT_INFO = CfgNode()
    cfg.POINT_INFO.ENABLE = True
    cfg.POINT_INFO.GRID_SIZE = 16
    cfg.POINT_INFO.NAME = ''
    cfg.POINT_INFO.NUM_POINTS_TO_SAMPLE = 256
    cfg.POINT_INFO.SAMPLING_TYPE = 'random'
    cfg.POINT_INFO.PT_FIX_SAMPLING_TRAIN = False
    cfg.POINT_INFO.PT_FIX_SAMPLING_TEST = False
    cfg.POINT_INFO.USE_PT_QUERY_MASK = False
    cfg.POINT_INFO.OBJ_ID_KEY = 'obj_ids'
    cfg.POINT_INFO.HOD = CfgNode()
    cfg.POINT_INFO.HOD.NUM_BINS = 32
    cfg.POINT_INFO.HOD.NUM_CLUSTERS = 16
    cfg.POINT_INFO.HOD_MIN = True
    cfg.POINT_INFO.HOD.GET_FEAT = True
    cfg.POINT_INFO.HOD.TEMPORAL_PYRAMID = False
    cfg.POINT_INFO.HOD.TEMPORAL_PYRAMID_LEVELS = 3
    cfg.POINT_INFO.HOD.PRESERVE_TEMPORAL = True
    cfg.POINT_INFO.USE_CORRELATION = False

    # motion module config
    cfg.MODEL.MOTION_MODULE = CfgNode()
    cfg.MODEL.MOTION_MODULE.USE_CROSS_MOTION_MODULE = False
    cfg.MODEL.MOTION_MODULE.USE_HOD_MOTION_MODULE = False
    cfg.MODEL.APPEARANCE_MODULE_DISABLE = False

    return cfg
